--- 
clone: 
  depth: 1
kind: pipeline
name: NxthaPipeline
concurrency:
  limit: 6
steps: 
  - 
    environment: 
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      GIT_SECRET:
        from_secret: GIT_SECRET
      GIT_SECRETB:
        from_secret: GIT_SECRETB
      GIT_USERNAME:
        from_secret: GIT_USERNAME
    image: archlinux:base-devel
    name: Nxtha-Build
    commands: 
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - pacman -Sy && pacman -S git bc inetutils python2 zip wget cpio jdk-openjdk tzdata --noconfirm
      - ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
      - "bash ./do-main.sh"